# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=datetime.datetime(2016, 6, 10, 3, 48, 25, 746373, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
